import React, { useState, useRef, useCallback, useEffect } from 'react'
import { Link, useNavigate, useParams, useLocation } from 'react-router-dom'
import AppShell from '../components/AppShell'
import LightningButton from '../components/LightningButton'
import { useProjects } from '../contexts/ProjectsContext'
import { analyzeDesign, generateFixPrompt, generateAsset } from '../lib/gemini'
import './PromptEditor.css'

const TOOL_EXPORTS = [
  { cat: 'Coding Agents', tools: [
    { name: 'Cursor',     icon: '⬡', desc: 'Paste into Composer to scaffold.' },
    { name: 'Claude Code',icon: '◆', desc: 'Run `claude` in terminal, paste prompt.' },
    { name: 'Windsurf',   icon: '▲', desc: 'Open Cascade and paste.' },
  ]},
  { cat: 'App Builders', tools: [
    { name: 'Bolt',    icon: '⚡', desc: 'Generate a full-stack app.',        url: 'https://bolt.new' },
    { name: 'v0',      icon: '▸', desc: 'React + Tailwind components.',       url: 'https://v0.dev' },
    { name: 'Lovable', icon: '♥', desc: 'Build a full app visually.',         url: 'https://lovable.dev' },
  ]},
  { cat: 'AI Assistants', tools: [
    { name: 'ChatGPT', icon: '◎', desc: 'Code generation.',               url: 'https://chat.openai.com' },
    { name: 'Claude',  icon: '◆', desc: 'Implementation guidance.',        url: 'https://claude.ai' },
    { name: 'Gemini',  icon: '✦', desc: 'Code generation.',               url: 'https://gemini.google.com' },
  ]},
]

const DESIGN_TYPES = [
  'None (auto-detect)', 'Landing Page', 'Dashboard', 'E-commerce',
  'SaaS App', 'Mobile App', 'Portfolio', 'Blog', 'Admin Panel',
]

// ── Asset icon by type ────────────────────────────────────────────────────────
const ASSET_TYPE_ICON = {
  Photo: (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
      <rect x="1" y="1" width="14" height="14" rx="3" stroke="currentColor" strokeWidth="1.3"/>
      <circle cx="5.5" cy="5.5" r="1.5" stroke="currentColor" strokeWidth="1.2"/>
      <path d="M1.5 12l3.5-3.5 3 3 2-2 4.5 4.5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  ),
  Icon: (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
      <path d="M8 1l1.8 4 4.2.6-3 3 .7 4.2L8 11l-3.7 1.8.7-4.2-3-3L6.2 5z" stroke="currentColor" strokeWidth="1.2" strokeLinejoin="round"/>
    </svg>
  ),
  Illustration: (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
      <path d="M2 12 C4 8 6 6 8 8 C10 10 12 4 14 4" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/>
      <circle cx="8" cy="8" r="1.5" fill="currentColor" opacity="0.4"/>
    </svg>
  ),
}

// ── Parse assets from spec text ───────────────────────────────────────────────
function parseAssets(spec) {
  if (!spec) return []
  const patterns = [
    { re: /logo|brand\s*icon/i,            type: 'Icon',  label: 'Brand / Logo icon' },
    { re: /hero\s*image|banner\s*image/i,  type: 'Photo', label: 'Hero / banner image' },
    { re: /avatar|profile\s*(photo|pic)/i, type: 'Icon',  label: 'User avatar / profile icon' },
    { re: /user\s*icon|profile\s*icon/i,   type: 'Icon',  label: 'Minimalist user/profile icon, line style' },
    { re: /shopping\s*(bag|cart)/i,        type: 'Icon',  label: 'Minimalist shopping bag icon, line style' },
    { re: /play\s*button|video\s*play/i,   type: 'Icon',  label: 'Play button (circle with triangle), line style' },
    { re: /arrow\s*(left|back|prev)/i,     type: 'Icon',  label: 'Left arrow icon, line style' },
    { re: /arrow\s*(right|next|fwd)/i,     type: 'Icon',  label: 'Right arrow icon, line style' },
    { re: /search\s*icon/i,                type: 'Icon',  label: 'Search / magnifier icon, line style' },
    { re: /menu|hamburger/i,               type: 'Icon',  label: 'Hamburger menu icon, line style' },
    { re: /basketball/i,                   type: 'Photo', label: 'Realistic 3D basketball, centered, with subtle drop shadow' },
    { re: /notification|bell\s*icon/i,     type: 'Icon',  label: 'Notification bell icon, line style' },
    { re: /chart|graph|analytics/i,        type: 'Icon',  label: 'Analytics chart icon, line style' },
  ]
  const seen = new Set()
  const assets = []
  for (const line of spec.split('\n')) {
    for (const { re, type, label } of patterns) {
      if (re.test(line) && !seen.has(label)) {
        seen.add(label)
        assets.push({ type, label, status: 'pending', result: null, resultType: null })
      }
    }
  }
  return assets.slice(0, 8)
}

// ── Export prompt as .md file ─────────────────────────────────────────────────
function exportMarkdown(promptText, projectName) {
  const md = `# ${projectName}\n\n> Generated by SHAZAM — ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}\n\n---\n\n${promptText}`
  const blob = new Blob([md], { type: 'text/markdown' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `${projectName.replace(/\s+/g, '-').toLowerCase()}-spec.md`
  a.click()
  URL.revokeObjectURL(url)
}

// ── Upload Zone ───────────────────────────────────────────────────────────────
function UploadZone({ files, onFiles, onRemove }) {
  const [dragging, setDragging] = useState(false)
  const inputRef = useRef()

  const handleDrop = useCallback((e) => {
    e.preventDefault()
    setDragging(false)
    const dropped = Array.from(e.dataTransfer.files).filter(f => f.type.startsWith('image/'))
    if (dropped.length) onFiles(dropped)
  }, [onFiles])

  return (
    <div className="upload-area">
      <div
        className={`upload-zone ${dragging ? 'upload-zone--drag' : ''}`}
        onDragOver={e => { e.preventDefault(); setDragging(true) }}
        onDragLeave={() => setDragging(false)}
        onDrop={handleDrop}
        onClick={() => !files.length && inputRef.current?.click()}
      >
        <input
          ref={inputRef}
          type="file"
          accept="image/*"
          multiple
          hidden
          onChange={e => onFiles(Array.from(e.target.files))}
        />

        {files.length === 0 ? (
          <>
            <div className="upload-zone__icon">
              <svg width="40" height="40" viewBox="0 0 40 40" fill="none">
                <rect x="3" y="3" width="34" height="34" rx="9" stroke="currentColor" strokeWidth="1.6"/>
                <path d="M20 12v16M12 20l8-8 8 8" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </div>
            <p className="upload-zone__title">Drop your design here or click to browse</p>
            <p className="upload-zone__sub">PNG, JPG, WebP — up to 5 images</p>
          </>
        ) : (
          <div className="upload-thumbs" onClick={e => e.stopPropagation()}>
            {files.map((file, i) => (
              <div key={i} className="upload-thumb">
                <img
                  src={URL.createObjectURL(file)}
                  alt={file.name}
                  className="upload-thumb__img"
                />
                <button
                  className="upload-thumb__remove"
                  onClick={e => { e.stopPropagation(); onRemove(i) }}
                >×</button>
                <span className="upload-thumb__name">{file.name}</span>
              </div>
            ))}
            {files.length < 5 && (
              <button
                className="upload-thumb-add"
                onClick={e => { e.stopPropagation(); inputRef.current?.click() }}
              >
                <svg width="22" height="22" viewBox="0 0 22 22" fill="none">
                  <path d="M11 4v14M4 11h14" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
                </svg>
                <span>Add more</span>
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

// ── Asset Card ────────────────────────────────────────────────────────────────
function AssetCard({ asset, onGenerate }) {
  const [copied, setCopied] = useState(false)

  const handleCopyResult = () => {
    navigator.clipboard?.writeText(asset.result || '')
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  return (
    <div className="asset-card">
      <div className="asset-card__top">
        <div className="asset-card__icon-wrap">
          {ASSET_TYPE_ICON[asset.type] || ASSET_TYPE_ICON.Icon}
        </div>
        <div className="asset-card__meta">
          <span className="asset-card__type">{asset.type}</span>
          <span className={`asset-card__status asset-card__status--${asset.status}`}>
            {asset.status === 'done' ? 'Generated' :
             asset.status === 'generating' ? 'Generating...' :
             asset.status === 'error' ? 'Failed' : 'Pending'}
          </span>
        </div>
      </div>

      <p className="asset-card__label">{asset.label}</p>

      {asset.status === 'done' && asset.result ? (
        <div className="asset-card__result">
          {asset.resultType === 'svg' ? (
            <div
              className="asset-card__svg-preview"
              dangerouslySetInnerHTML={{ __html: asset.result.replace(/currentColor/g, 'white') }}
            />
          ) : (
            <p className="asset-card__image-prompt">{asset.result.slice(0, 100)}…</p>
          )}
          <button className={`asset-card__copy ${copied ? 'asset-card__copy--done' : ''}`} onClick={handleCopyResult}>
            {copied ? '✓ Copied' : asset.resultType === 'svg' ? 'Copy SVG' : 'Copy Prompt'}
          </button>
        </div>
      ) : (
        <button
          className="asset-card__generate-btn"
          onClick={() => onGenerate(asset)}
          disabled={asset.status === 'generating'}
        >
          {asset.status === 'generating' ? (
            <><span className="editor__spinner" style={{width:12,height:12,borderWidth:1.5}}/>Generating</>
          ) : (
            <><span className="asset-card__sparkle">✦</span> Generate</>
          )}
        </button>
      )}
    </div>
  )
}

// ── Prompt Preview ────────────────────────────────────────────────────────────
function PromptPreview({ text }) {
  return (
    <div className="preview-body">
      {text.split('\n').map((line, i) => {
        if (!line.trim()) return <div key={i} className="preview-spacer" />
        const isBold = line.startsWith('**') && line.endsWith('**')
        if (isBold) return <p key={i} className="preview-heading">{line.replace(/\*\*/g, '')}</p>
        if (/^[A-Z][A-Za-z\s&\/\-]{2,50}$/.test(line.trim()) && i < 80) {
          return <p key={i} className="preview-heading">{line}</p>
        }
        return <p key={i} className="preview-line">{line}</p>
      })}
    </div>
  )
}

// ── Main Page ─────────────────────────────────────────────────────────────────
export default function PromptEditor() {
  const { id }       = useParams()
  const navigate     = useNavigate()
  const location     = useLocation()
  const { projects, addProject, updateProject, getProject, trackUsage, getUsageThisMonth } = useProjects()

  const isNew           = id === 'new'
  const existingProject = isNew ? null : getProject(id)  // id may be _id from MongoDB
  const templatePrompt  = location.state?.templatePrompt || ''
  const templateName    = location.state?.templateName   || ''

  const [files, setFiles]             = useState([])
  const [promptText, setPromptText]   = useState(existingProject?.prompt || templatePrompt)
  const [editMode, setEditMode]       = useState(!!templatePrompt)
  const [designType, setDesignType]   = useState(existingProject?.designType || 'None (auto-detect)')
  const [analyzing, setAnalyzing]     = useState(false)
  const [analysisError, setAnalysisError] = useState('')
  const [analyzed, setAnalyzed]       = useState(!isNew && !!existingProject?.prompt || !!templatePrompt)
  const [projectName, setProjectName] = useState(existingProject?.name || templateName || 'Untitled Project')
  const [editingName, setEditingName] = useState(false)
  const [liveUrl, setLiveUrl]         = useState(existingProject?.liveUrl || '')
  const [fixIssue, setFixIssue]       = useState('')
  const [fixScreenshot, setFixScreenshot] = useState(null) // { file, preview }
  const [fixResult, setFixResult]     = useState('')
  const [generatingFix, setGeneratingFix] = useState(false)
  const [saved, setSaved]             = useState(false)
  const [copied, setCopied]           = useState('')
  const [currentProjectId, setCurrentProjectId] = useState(existingProject?._id || existingProject?.id || null)
  const [assets, setAssets]           = useState(existingProject?.assets || [])
  const [thumbnail, setThumbnail]     = useState(existingProject?.thumbnail || null)

  const fixScreenshotRef = useRef()

  // Parse assets when spec is loaded or analyzed
  useEffect(() => {
    if (promptText && analyzed && assets.length === 0) {
      setAssets(parseAssets(promptText))
    }
  }, [promptText, analyzed])

  const handleFiles      = (f) => setFiles(prev => [...prev, ...f].slice(0, 5))
  const handleRemoveFile = (i) => setFiles(prev => prev.filter((_, j) => j !== i))

  const generateThumbnail = (file) => new Promise(resolve => {
    const reader = new FileReader()
    reader.onload = e => {
      const img = new Image()
      img.onload = () => {
        const canvas = document.createElement('canvas')
        const max = 400
        const r = Math.min(max / img.width, max / img.height)
        canvas.width = img.width * r
        canvas.height = img.height * r
        canvas.getContext('2d').drawImage(img, 0, 0, canvas.width, canvas.height)
        resolve(canvas.toDataURL('image/jpeg', 0.75))
      }
      img.onerror = () => resolve(null)
      img.src = e.target.result
    }
    reader.onerror = () => resolve(null)
    reader.readAsDataURL(file)
  })

  const handleAnalyze = async () => {
    if (files.length === 0) { setAnalysisError('Please upload at least one design image.'); return }
    if (isNew && projects.length >= 5) { setAnalysisError('You have reached the 5 project limit on the free plan. Delete a project to create a new one.'); return }
    if (getUsageThisMonth() >= 20) { setAnalysisError('You have used all 20 AI actions for this month. Your limit resets next month.'); return }
    setAnalyzing(true); setAnalysisError('')
    try {
      const result = await analyzeDesign(files, null, designType)
      const thumb  = await generateThumbnail(files[0])
      const parsed = parseAssets(result)
      setPromptText(result)
      setAnalyzed(true)
      setThumbnail(thumb)
      setAssets(parsed)
      const projData = { name: projectName, prompt: result, designType, imageCount: files.length, liveUrl, thumbnail: thumb, assets: parsed }
      if (currentProjectId) {
        updateProject(currentProjectId, projData)
      } else {
        const newProj = await addProject(projData)
        const projId = newProj._id || newProj.id
        setCurrentProjectId(projId)
        navigate(`/editor/${projId}`, { replace: true })
      }
    } catch (err) {
      setAnalysisError(err.message)
    } finally {
      setAnalyzing(false)
    }
  }

  const handleSave = () => {
    if (currentProjectId) updateProject(currentProjectId, { name: projectName, prompt: promptText, designType, liveUrl, assets })
    setSaved(true); setTimeout(() => setSaved(false), 2000)
  }

  const handleExport = () => exportMarkdown(promptText, projectName)

  const handleCopy = (text, key) => {
    navigator.clipboard?.writeText(text)
    setCopied(key)
    setTimeout(() => setCopied(''), 1500)
  }

  const handleGenerateFix = async () => {
    if (!fixIssue.trim()) return
    if (getUsageThisMonth() >= 20) { setFixResult('Error: You have used all 20 AI actions for this month. Your limit resets next month.'); return }
    setGeneratingFix(true); setFixResult('')
    try {
      const r = await generateFixPrompt(promptText, fixIssue, null)
      setFixResult(r)
      trackUsage() // fix prompt = 1 usage
    } catch (err) {
      setFixResult(`Error: ${err.message}`)
    } finally {
      setGeneratingFix(false)
    }
  }

  const handleFixScreenshot = (e) => {
    const file = e.target.files?.[0]
    if (!file) return
    const preview = URL.createObjectURL(file)
    setFixScreenshot({ file, preview })
  }

  const handleGenerateAsset = async (asset) => {
    if (getUsageThisMonth() >= 20) {
      setAssets(prev => prev.map(a => a.label === asset.label ? { ...a, status: 'error' } : a))
      return
    }
    setAssets(prev => prev.map(a => a.label === asset.label ? { ...a, status: 'generating' } : a))
    try {
      const { result, type: resultType } = await generateAsset(asset.label, asset.type)
      const updated = assets.map(a =>
        a.label === asset.label ? { ...a, status: 'done', result, resultType } : a
      )
      setAssets(updated)
      if (currentProjectId) updateProject(currentProjectId, { assets: updated })
      trackUsage() // asset generate = 1 usage
    } catch {
      setAssets(prev => prev.map(a => a.label === asset.label ? { ...a, status: 'error' } : a))
    }
  }

  const handleNameBlur = () => {
    setEditingName(false)
    if (currentProjectId) updateProject(currentProjectId, { name: projectName })
  }

  return (
    <AppShell>
      <div className="editor">

        {/* ── Top bar ── */}
        <div className="editor__topbar">
          <div className="editor__breadcrumb">
            <Link to="/dashboard" className="editor__breadcrumb-link">Dashboard</Link>
            <span className="editor__breadcrumb-sep">/</span>
            {editingName ? (
              <input
                className="editor__name-input"
                value={projectName}
                autoFocus
                onChange={e => setProjectName(e.target.value)}
                onBlur={handleNameBlur}
                onKeyDown={e => e.key === 'Enter' && setEditingName(false)}
              />
            ) : (
              <button className="editor__name-btn" onClick={() => setEditingName(true)}>
                {projectName}
                <svg width="11" height="11" viewBox="0 0 11 11" fill="none" style={{marginLeft:5,opacity:0.45}}>
                  <path d="M7.5 1L9.5 3l-5.5 5.5H2V6l5.5-5z" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
              </button>
            )}
          </div>

          <div className="editor__topbar-right">
            {analyzed && (
              <span className="editor__save-status">{saved ? '✓ Saved' : 'All changes saved'}</span>
            )}
            <div className="editor__topbar-actions">
              {analyzed && (
                <button className="editor__action-btn editor__action-btn--ghost" onClick={handleSave}>
                  Save
                </button>
              )}
              {analyzed && (
                <button
                  className={`editor__action-btn editor__action-btn--ghost ${copied === 'main' ? 'editor__action-btn--copied' : ''}`}
                  onClick={() => handleCopy(promptText, 'main')}
                >
                  {copied === 'main' ? '✓ Copied' : 'Copy'}
                </button>
              )}
              {analyzed && (
                <button className="editor__action-btn editor__action-btn--ghost" onClick={handleExport}>
                  <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
                    <path d="M6.5 1v8M3.5 6l3 3 3-3" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
                    <path d="M1 9.5v1A1.5 1.5 0 002.5 12h8a1.5 1.5 0 001.5-1.5v-1" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/>
                  </svg>
                  Export .md
                </button>
              )}
            </div>
          </div>
        </div>

        {/* ── Layout ── */}
        <div className="editor__layout">

          {/* ── Main column ── */}
          <div className="editor__main">
            {analyzed ? (
              <>
                {/* Master Prompt card */}
                <div className="editor__card">
                  <div className="editor__card-header">
                    <div className="editor__card-header-left">
                      <svg width="15" height="15" viewBox="0 0 15 15" fill="none">
                        <rect x="1" y="2" width="13" height="11" rx="2" stroke="currentColor" strokeWidth="1.3"/>
                        <path d="M4 6h7M4 9h5" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/>
                      </svg>
                      <h2 className="editor__card-title">Master Prompt</h2>
                    </div>
                    <div className="editor__tab-group">
                      <button className={`editor__tab ${!editMode ? 'editor__tab--active' : ''}`} onClick={() => setEditMode(false)}>Preview</button>
                      <button className={`editor__tab ${editMode ? 'editor__tab--active' : ''}`} onClick={() => setEditMode(true)}>Edit</button>
                    </div>
                  </div>
                  <p className="editor__card-sub">Rendered preview of the generated prompt.</p>

                  {editMode ? (
                    <textarea
                      className="editor__textarea"
                      value={promptText}
                      onChange={e => setPromptText(e.target.value)}
                      spellCheck={false}
                    />
                  ) : (
                    <div className="editor__preview">
                      <div className="editor__preview-intro">
                        Act as a senior engineer. Prioritize accuracy over creativity. Do not introduce ideas that aren't in the reference.
                      </div>
                      <PromptPreview text={promptText} />
                    </div>
                  )}
                </div>

                {/* Fix Prompt card */}
                <div className="editor__card">
                  <div className="editor__card-header-left" style={{marginBottom:6}}>
                    <svg width="15" height="15" viewBox="0 0 15 15" fill="none">
                      <path d="M12 1.5L3 10.5M7 1.5H1.5V7" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                    <h2 className="editor__card-title">Fix Prompt</h2>
                  </div>
                  <p className="editor__card-sub" style={{marginBottom:14}}>
                    Something off? Describe the issue and get a separate fix prompt to paste into your AI tool.
                  </p>

                  <textarea
                    className="editor__fix-input"
                    rows={3}
                    placeholder="e.g. The hero section spacing is too tight, the font size for headings should be larger..."
                    value={fixIssue}
                    onChange={e => setFixIssue(e.target.value)}
                  />

                  {/* Fix screenshot preview */}
                  {fixScreenshot && (
                    <div className="editor__fix-screenshot-preview">
                      <img src={fixScreenshot.preview} alt="Screenshot" className="editor__fix-screenshot-img"/>
                      <button className="editor__fix-screenshot-remove" onClick={() => setFixScreenshot(null)}>
                        <svg width="10" height="10" viewBox="0 0 10 10" fill="none">
                          <path d="M1 1l8 8M9 1L1 9" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/>
                        </svg>
                      </button>
                    </div>
                  )}

                  <div className="editor__fix-actions">
                    <button
                      className="editor__fix-screenshot-btn"
                      onClick={() => fixScreenshotRef.current?.click()}
                    >
                      <input
                        ref={fixScreenshotRef}
                        type="file"
                        accept="image/*"
                        hidden
                        onChange={handleFixScreenshot}
                      />
                      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                        <rect x="1" y="2" width="12" height="10" rx="2" stroke="currentColor" strokeWidth="1.2"/>
                        <circle cx="7" cy="7" r="2" stroke="currentColor" strokeWidth="1.2"/>
                      </svg>
                      {fixScreenshot ? 'Change screenshot' : 'Add screenshot'}
                    </button>
                    <button
                      className="editor__action-btn"
                      style={{opacity: fixIssue.trim() ? 1 : 0.45}}
                      onClick={handleGenerateFix}
                      disabled={!fixIssue.trim() || generatingFix}
                    >
                      {generatingFix
                        ? <><span className="editor__spinner"/>Generating...</>
                        : 'Generate Fix Prompt'}
                    </button>
                  </div>

                  {fixResult && (
                    <div className="editor__fix-result">
                      <div className="editor__fix-result-header">
                        <span>Fix Prompt</span>
                        <button onClick={() => handleCopy(fixResult, 'fix')}>
                          {copied === 'fix' ? '✓ Copied' : 'Copy'}
                        </button>
                      </div>
                      <p>{fixResult}</p>
                    </div>
                  )}
                </div>

                {/* Use Your Prompt */}
                <div className="editor__card">
                  <div className="editor__card-header-left" style={{marginBottom:6}}>
                    <svg width="15" height="15" viewBox="0 0 15 15" fill="none">
                      <path d="M9 1.5H4a2 2 0 00-2 2v8a2 2 0 002 2h7a2 2 0 002-2V6l-4-4.5z" stroke="currentColor" strokeWidth="1.3"/>
                      <path d="M9 1.5V6H13.5" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/>
                    </svg>
                    <h2 className="editor__card-title">Use Your Prompt</h2>
                  </div>
                  <p className="editor__card-sub" style={{marginBottom:20}}>
                    Copy the prompt and use it in your preferred tool to start building.
                  </p>

                  {TOOL_EXPORTS.map((group, gi) => (
                    <div key={gi} className="editor__tool-group">
                      <div className="editor__tool-group-label">{group.cat}</div>
                      <div className="editor__tools">
                        {group.tools.map((tool, ti) => (
                          <div key={ti} className="editor__tool">
                            <div className="editor__tool-icon">{tool.icon}</div>
                            <div className="editor__tool-info">
                              <span className="editor__tool-name">{tool.name}</span>
                              <span className="editor__tool-desc">{tool.desc}</span>
                            </div>
                            <div className="editor__tool-btns">
                              <button
                                className={`editor__tool-copy ${copied===`t${gi}${ti}`?'editor__tool-copy--copied':''}`}
                                onClick={() => handleCopy(promptText, `t${gi}${ti}`)}
                              >
                                {copied===`t${gi}${ti}` ? '✓' : 'Copy'}
                              </button>
                              {tool.url && (
                                <a href={tool.url} target="_blank" rel="noreferrer" className="editor__tool-open">
                                  Open ↗
                                </a>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}

                  <div className="editor__live">
                    <label className="editor__live-label">Live Version</label>
                    <p className="editor__card-sub" style={{marginBottom:8}}>Connect your deployed result.</p>
                    <input
                      className="editor__live-input"
                      placeholder="https://your-app.vercel.app"
                      value={liveUrl}
                      onChange={e => setLiveUrl(e.target.value)}
                    />
                  </div>
                </div>
              </>
            ) : (
              /* Upload + Analyze */
              <div className="editor__card">
                <h2 className="editor__card-title" style={{marginBottom:4}}>New Prompt</h2>
                <p className="editor__card-sub" style={{marginBottom:24}}>
                  Upload reference designs or screen recordings and generate a strict implementation prompt.
                </p>

                <p className="editor__step-label">Step 1: Upload References</p>
                <UploadZone files={files} onFiles={handleFiles} onRemove={handleRemoveFile} />

                {analysisError && (
                  <div className="editor__error">
                    <svg width="15" height="15" viewBox="0 0 15 15" fill="none">
                      <circle cx="7.5" cy="7.5" r="6.5" stroke="currentColor" strokeWidth="1.3"/>
                      <path d="M7.5 4.5v3.5M7.5 10v.5" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/>
                    </svg>
                    {analysisError}
                  </div>
                )}

                <LightningButton
                  onClick={handleAnalyze}
                  loading={analyzing}
                  disabled={files.length === 0}
                  className="editor__analyze-lbtn"
                >
                  Shazam It!
                </LightningButton>

                {analyzing && (
                  <div className="editor__steps">
                    {[
                      'Reading visual layout...',
                      'Extracting typography & colors...',
                      'Mapping components...',
                      'Writing implementation spec...',
                    ].map((s, i) => (
                      <div key={i} className="editor__step" style={{animationDelay:`${i*0.7}s`}}>
                        <span className="editor__step-dot"/>
                        {s}
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="editor__sidebar">
            {/* Design Type */}
            <div className="editor__card">
              <div className="editor__sidebar-header">
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                  <rect x="1" y="1" width="12" height="12" rx="2.5" stroke="currentColor" strokeWidth="1.2"/>
                  <path d="M3.5 4.5h7M3.5 7h5M3.5 9.5h6" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/>
                </svg>
                <h3 className="editor__sidebar-title">Design Type</h3>
              </div>
              <p className="editor__card-sub" style={{marginBottom:10}}>
                Auto-detected from your design. Override if needed.
              </p>
              <select
                className="editor__type-select"
                value={designType}
                onChange={e => setDesignType(e.target.value)}
              >
                {DESIGN_TYPES.map(t => <option key={t} value={t}>{t}</option>)}
              </select>
            </div>

            {/* Reference Images */}
            {(thumbnail || existingProject?.imageCount > 0) && (
              <div className="editor__card">
                <div className="editor__sidebar-header">
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                    <rect x="1" y="1" width="12" height="12" rx="2.5" stroke="currentColor" strokeWidth="1.2"/>
                    <circle cx="4.5" cy="5" r="1.5" stroke="currentColor" strokeWidth="1.1"/>
                    <path d="M1.5 10.5l3-3 2.5 2.5 2-2 3.5 3.5" stroke="currentColor" strokeWidth="1.1" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                  <h3 className="editor__sidebar-title">Reference Images</h3>
                </div>
                <p className="editor__card-sub" style={{marginBottom:12}}>
                  The uploaded screens that produced this prompt.
                </p>
                <div className="editor__ref-images">
                  {thumbnail ? (
                    <div className="editor__ref-img-container">
                      <img src={thumbnail} alt="Reference" className="editor__ref-img" />
                      <div className="editor__ref-img-footer">
                        {existingProject?.name || projectName} reference 1
                      </div>
                    </div>
                  ) : (
                    <div className="editor__ref-placeholder">
                      <svg width="28" height="28" viewBox="0 0 28 28" fill="none">
                        <rect x="2" y="2" width="24" height="24" rx="6" stroke="currentColor" strokeWidth="1.3"/>
                        <circle cx="9" cy="10" r="2.5" stroke="currentColor" strokeWidth="1.2"/>
                        <path d="M3 22l6-6 4 4 3-3 8 8" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/>
                      </svg>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Assets */}
            {analyzed && (
              <div className="editor__card">
                <div className="editor__sidebar-header">
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                    <rect x="1" y="1" width="12" height="12" rx="2.5" stroke="currentColor" strokeWidth="1.2"/>
                    <path d="M7 3.5V7l2 2" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/>
                  </svg>
                  <h3 className="editor__sidebar-title">Assets</h3>
                  <span className="editor__assets-count">{assets.length}</span>
                </div>
                <p className="editor__card-sub" style={{marginBottom:14}}>
                  Custom assets identified in the design. Generate them with AI.
                </p>
                {assets.length === 0 ? (
                  <p className="editor__card-sub">No assets detected in this spec.</p>
                ) : (
                  <div className="editor__assets-list">
                    {assets.map((asset, i) => (
                      <AssetCard key={i} asset={asset} onGenerate={handleGenerateAsset} />
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* Spec stats */}
            {analyzed && (
              <div className="editor__card">
                <div className="editor__sidebar-header">
                  <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                    <path d="M2 11V8M5 11V5M8 11V7M11 11V3" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round"/>
                  </svg>
                  <h3 className="editor__sidebar-title">Spec Info</h3>
                </div>
                <div className="editor__spec-stats">
                  <div className="editor__spec-stat">
                    <span className="editor__spec-stat-val">{promptText.split(' ').length.toLocaleString()}</span>
                    <span className="editor__spec-stat-label">words</span>
                  </div>
                  <div className="editor__spec-stat">
                    <span className="editor__spec-stat-val">{promptText.split('\n').filter(Boolean).length}</span>
                    <span className="editor__spec-stat-label">lines</span>
                  </div>
                  <div className="editor__spec-stat">
                    <span className="editor__spec-stat-val">{Math.ceil(promptText.length / 4).toLocaleString()}</span>
                    <span className="editor__spec-stat-label">tokens</span>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </AppShell>
  )
}
